version: '3'

services:
    frontend:
      image: front-end:v2
      ports: 
        - 5000:5000

    backend:
      image: back-end:v2
      environment:
        - REDIS_HOST=redis-server
      ports:
        - 8080:8080

    redis:
      image: redis
      container_name: redis-server
