version: '3.5'

services:

  frontend:
    image: front-end
    ports:
      - 5000:5000

  backend:
    image: back-end
    environment:
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=db_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 1234:8080
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: redis-server
    restart: unless-stopped
    volumes:
      - ./cache:/data
    ports:
      - 6379:6379

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db_backend
    ports:
      - 5432:5432

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx-proxy
    ports:
      - 80:80
