version: '3.5'

services:
    frontend:
      image: frontend:v3
      ports: 
        - 5000:5000

    backend:
      image: back-end:v2
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=postgres
      ports:
        - 8080:8080
      depends_on:
        - db
        - redis

    redis:
      image: redis
      container_name: redis-server
      volumes:
        - cache:/data
      ports:
        - 6379:6379

    db:
      image: postgres:alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - database:/var/lib/postgresql/data
      container_name: db_backend

    nginx:
      image: nginx:alpine
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      container_name: nginx-proxy
      ports: 
        - 80:80

volumes:
  database:
  cache:
