version: '3.5'

services:
    frontend:
      image: front-end:v2
      ports: 
        - 5000:5000

    backend:
      image: back-end:v2
      environment:
        - REDIS_HOST=redis-server
        - POSTGRES_HOST=db_backend 
        - POSTGRES_PASSWORD=postgres
      ports:
        - 8080:8080

    redis:
      image: redis
      container_name: redis-server


    db:
      image: postgres:alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: db_backend
