version: '3.5'

services:

  frontend:
    image: front-end
    ports:
      - 5000:5000

  backend:
    image: back-end
    environment:
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=db_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 1234:8080

  redis:
    image: redis
    container_name: redis-server
    restart: unless-stopped

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: db_backend
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
